version: '3.8'
services:
  backend:
    build: ./backend
    container_name: mavluda-backend
    restart: always
    ports:
      - "3000:4100"
    volumes:
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
    networks:
      - mavluda-network
  frontend:
    build: ./frontend
    container_name: mavluda-frontend
    ports:
      - "8088:80"
    volumes:
      - ./backend/uploads:/usr/share/nginx/html/uploads
    networks:
      - mavluda-network
    depends_on:
      - backend

networks:
  mavluda-network:
    driver: bridge