name: Build Backend NestJS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend/**"

permissions: 
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone Project
        uses: actions/checkout@v4 # Используем мажорную версию v4 для стабильности
        
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "backend/package-lock.json"
        
      - name: Install Dependencies
        run: | 
          cd backend
          npm ci --legacy-peer-deps
        
      - name: Build Backend NestJS
        run: |
          cd backend
          npm run build
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4 # Обязательно @v4
        with:
          folder: backend/dist
          branch: gh-backend
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true