name: Build Backend NestJS

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

permissions: 
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone Project on VR Machine
        uses: actions/checkout@4.2.2
        
      - name: Setup NodeJS on VR Machine
        uses: actions/setup-node@4.2.2
        with: 
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "backend/package-lock.json"
        
      - name: Install Dependencies
        run: | 
          cd backend
          npm run ci
        
      - name: Build Backend NestJS
        run: |
          cd backend
          npm run build --omit=production
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.4.0
        with:
          folder: backend/dist
          branch: gh-backend
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
      
      