name: Build Frontend Angular

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "frontend/**"
      - "backend/**"

permissions: 
  contents: write

jobs:
  deploy_frontend:
    uses: ./.github/workflows/frontend-deploy.yml
    secrets: inherit
    
  deploy_backend:
    uses: ./.github/workflows/backend-deploy.yml
    secrets: inherit
    